#ifndef INFO_GEN_H_
#define INFO_GEN_H_

#define _INFO_EVAL(...) _INFO_EVAL1(_INFO_EVAL1(_INFO_EVAL1(__VA_ARGS__)))
#define _INFO_EVAL1(...) _INFO_EVAL2(_INFO_EVAL2(_INFO_EVAL2(__VA_ARGS__)))
#define _INFO_EVAL2(...) _INFO_EVAL3(_INFO_EVAL3(_INFO_EVAL3(__VA_ARGS__)))
#define _INFO_EVAL3(...) _INFO_EVAL4(_INFO_EVAL4(_INFO_EVAL4(__VA_ARGS__)))
#define _INFO_EVAL4(...) _INFO_EVAL5(_INFO_EVAL5(_INFO_EVAL5(__VA_ARGS__)))
#define _INFO_EVAL5(...) __VA_ARGS__

#define _INFO_EXPAND(...) __VA_ARGS__
#define _INFO_EXPAND2(...) _INFO_EXPAND(__VA_ARGS__)

#define _INFO_EMPTY()
#define _INFO_DEFER(M) M _INFO_EMPTY()
#define _INFO_DEFER2(M) M _INFO_DEFER _INFO_EMPTY ()()
#define _INFO_DEFER3(M) M _INFO_DEFER2 _INFO_EMPTY ()()
#define _INFO_DEFER4(M) M _INFO_DEFER3 _INFO_EMPTY ()()
#define _INFO_DEFER5(M) M _INFO_DEFER4 _INFO_EMPTY ()()
#define _INFO_DEFER6(M) M _INFO_DEFER5 _INFO_EMPTY ()()
#define _INFO_DEFER7(M) M _INFO_DEFER6 _INFO_EMPTY ()()
#define _INFO_DEFER8(M) M _INFO_DEFER7 _INFO_EMPTY ()()
#define _INFO_DEFER9(M) M _INFO_DEFER8 _INFO_EMPTY ()()
#define _INFO_DEFER10(M) M _INFO_DEFER9 _INFO_EMPTY ()()
#define _INFO_DEFER11(M) M _INFO_DEFER10 _INFO_EMPTY ()()
#define _INFO_DEFER12(M) M _INFO_DEFER11 _INFO_EMPTY ()()
#define _INFO_DEFER13(M) M _INFO_DEFER12 _INFO_EMPTY ()()
#define _INFO_DEFER14(M) M _INFO_DEFER13 _INFO_EMPTY ()()
#define _INFO_DEFER15(M) M _INFO_DEFER14 _INFO_EMPTY ()()
#define _INFO_DEFER16(M) M _INFO_DEFER15 _INFO_EMPTY ()()
#define _INFO_DEFER17(M) M _INFO_DEFER16 _INFO_EMPTY ()()
#define _INFO_DEFER18(M) M _INFO_DEFER17 _INFO_EMPTY ()()
#define _INFO_DEFER19(M) M _INFO_DEFER18 _INFO_EMPTY ()()
#define _INFO_DEFER20(M) M _INFO_DEFER19 _INFO_EMPTY ()()
#define _INFO_DEFER21(M) M _INFO_DEFER20 _INFO_EMPTY ()()
#define _INFO_DEFER22(M) M _INFO_DEFER21 _INFO_EMPTY ()()
#define _INFO_DEFER23(M) M _INFO_DEFER22 _INFO_EMPTY ()()
#define _INFO_DEFER24(M) M _INFO_DEFER23 _INFO_EMPTY ()()
#define _INFO_DEFER25(M) M _INFO_DEFER24 _INFO_EMPTY ()()
#define _INFO_DEFER26(M) M _INFO_DEFER25 _INFO_EMPTY ()()
#define _INFO_DEFER27(M) M _INFO_DEFER26 _INFO_EMPTY ()()
#define _INFO_DEFER28(M) M _INFO_DEFER27 _INFO_EMPTY ()()
#define _INFO_DEFER29(M) M _INFO_DEFER28 _INFO_EMPTY ()()
#define _INFO_DEFER30(M) M _INFO_DEFER29 _INFO_EMPTY ()()
#define _INFO_DEFER31(M) M _INFO_DEFER30 _INFO_EMPTY ()()
#define _INFO_DEFER32(M) M _INFO_DEFER31 _INFO_EMPTY ()()
#define _INFO_DEFER33(M) M _INFO_DEFER32 _INFO_EMPTY ()()
#define _INFO_DEFER34(M) M _INFO_DEFER33 _INFO_EMPTY ()()
#define _INFO_DEFER35(M) M _INFO_DEFER34 _INFO_EMPTY ()()
#define _INFO_DEFER36(M) M _INFO_DEFER35 _INFO_EMPTY ()()
#define _INFO_DEFER37(M) M _INFO_DEFER36 _INFO_EMPTY ()()
#define _INFO_DEFER38(M) M _INFO_DEFER37 _INFO_EMPTY ()()
#define _INFO_DEFER39(M) M _INFO_DEFER38 _INFO_EMPTY ()()
#define _INFO_DEFER40(M) M _INFO_DEFER39 _INFO_EMPTY ()()
#define _INFO_DEFER41(M) M _INFO_DEFER40 _INFO_EMPTY ()()
#define _INFO_DEFER42(M) M _INFO_DEFER41 _INFO_EMPTY ()()
#define _INFO_DEFER43(M) M _INFO_DEFER42 _INFO_EMPTY ()()
#define _INFO_DEFER44(M) M _INFO_DEFER43 _INFO_EMPTY ()()
#define _INFO_DEFER45(M) M _INFO_DEFER44 _INFO_EMPTY ()()
#define _INFO_DEFER46(M) M _INFO_DEFER45 _INFO_EMPTY ()()
#define _INFO_DEFER47(M) M _INFO_DEFER46 _INFO_EMPTY ()()
#define _INFO_DEFER48(M) M _INFO_DEFER47 _INFO_EMPTY ()()
#define _INFO_DEFER49(M) M _INFO_DEFER48 _INFO_EMPTY ()()
#define _INFO_DEFER50(M) M _INFO_DEFER49 _INFO_EMPTY ()()
#define _INFO_DEFER51(M) M _INFO_DEFER50 _INFO_EMPTY ()()
#define _INFO_DEFER52(M) M _INFO_DEFER51 _INFO_EMPTY ()()
#define _INFO_DEFER53(M) M _INFO_DEFER52 _INFO_EMPTY ()()
#define _INFO_DEFER54(M) M _INFO_DEFER53 _INFO_EMPTY ()()
#define _INFO_DEFER55(M) M _INFO_DEFER54 _INFO_EMPTY ()()
#define _INFO_DEFER56(M) M _INFO_DEFER55 _INFO_EMPTY ()()
#define _INFO_DEFER57(M) M _INFO_DEFER56 _INFO_EMPTY ()()
#define _INFO_DEFER58(M) M _INFO_DEFER57 _INFO_EMPTY ()()
#define _INFO_DEFER59(M) M _INFO_DEFER58 _INFO_EMPTY ()()
#define _INFO_DEFER60(M) M _INFO_DEFER59 _INFO_EMPTY ()()
#define _INFO_DEFER61(M) M _INFO_DEFER60 _INFO_EMPTY ()()
#define _INFO_DEFER62(M) M _INFO_DEFER61 _INFO_EMPTY ()()
#define _INFO_DEFER63(M) M _INFO_DEFER62 _INFO_EMPTY ()()
#define _INFO_DEFER64(M) M _INFO_DEFER63 _INFO_EMPTY ()()
#define _INFO_DEFER65(M) M _INFO_DEFER64 _INFO_EMPTY ()()
#define _INFO_DEFER66(M) M _INFO_DEFER65 _INFO_EMPTY ()()
#define _INFO_DEFER67(M) M _INFO_DEFER66 _INFO_EMPTY ()()
#define _INFO_DEFER68(M) M _INFO_DEFER67 _INFO_EMPTY ()()
#define _INFO_DEFER69(M) M _INFO_DEFER68 _INFO_EMPTY ()()
#define _INFO_DEFER70(M) M _INFO_DEFER69 _INFO_EMPTY ()()
#define _INFO_DEFER71(M) M _INFO_DEFER70 _INFO_EMPTY ()()
#define _INFO_DEFER72(M) M _INFO_DEFER71 _INFO_EMPTY ()()
#define _INFO_DEFER73(M) M _INFO_DEFER72 _INFO_EMPTY ()()
#define _INFO_DEFER74(M) M _INFO_DEFER73 _INFO_EMPTY ()()
#define _INFO_DEFER75(M) M _INFO_DEFER74 _INFO_EMPTY ()()
#define _INFO_DEFER76(M) M _INFO_DEFER75 _INFO_EMPTY ()()
#define _INFO_DEFER77(M) M _INFO_DEFER76 _INFO_EMPTY ()()
#define _INFO_DEFER78(M) M _INFO_DEFER77 _INFO_EMPTY ()()
#define _INFO_DEFER79(M) M _INFO_DEFER78 _INFO_EMPTY ()()
#define _INFO_DEFER80(M) M _INFO_DEFER79 _INFO_EMPTY ()()
#define _INFO_DEFER81(M) M _INFO_DEFER80 _INFO_EMPTY ()()
#define _INFO_DEFER82(M) M _INFO_DEFER81 _INFO_EMPTY ()()
#define _INFO_DEFER83(M) M _INFO_DEFER82 _INFO_EMPTY ()()
#define _INFO_DEFER84(M) M _INFO_DEFER83 _INFO_EMPTY ()()
#define _INFO_DEFER85(M) M _INFO_DEFER84 _INFO_EMPTY ()()
#define _INFO_DEFER86(M) M _INFO_DEFER85 _INFO_EMPTY ()()
#define _INFO_DEFER87(M) M _INFO_DEFER86 _INFO_EMPTY ()()
#define _INFO_DEFER88(M) M _INFO_DEFER87 _INFO_EMPTY ()()
#define _INFO_DEFER89(M) M _INFO_DEFER88 _INFO_EMPTY ()()
#define _INFO_DEFER90(M) M _INFO_DEFER89 _INFO_EMPTY ()()
#define _INFO_DEFER91(M) M _INFO_DEFER90 _INFO_EMPTY ()()
#define _INFO_DEFER92(M) M _INFO_DEFER91 _INFO_EMPTY ()()
#define _INFO_DEFER93(M) M _INFO_DEFER92 _INFO_EMPTY ()()
#define _INFO_DEFER94(M) M _INFO_DEFER93 _INFO_EMPTY ()()
#define _INFO_DEFER95(M) M _INFO_DEFER94 _INFO_EMPTY ()()
#define _INFO_DEFER96(M) M _INFO_DEFER95 _INFO_EMPTY ()()
#define _INFO_DEFER97(M) M _INFO_DEFER96 _INFO_EMPTY ()()
#define _INFO_DEFER98(M) M _INFO_DEFER97 _INFO_EMPTY ()()
#define _INFO_DEFER99(M) M _INFO_DEFER98 _INFO_EMPTY ()()
#define _INFO_DEFER100(M) M _INFO_DEFER99 _INFO_EMPTY ()()

#define _INFO_DEFER_N(N) _INFO_DEFER##N

#define _INFO_CAT_(a,b) a ## b
#define _INFO_CAT(a,b) _INFO_CAT_(a,b)

#define _INFO_CAT2_(a,b) a ## b
#define _INFO_CAT2(a,b) _INFO_CAT_(a,b)

#define _INFO_CHECK2(...) _INFO_CHECK_B2(__VA_ARGS__, 0,)
#define _INFO_CHECK_B2(a,b,...) b
#define _INFO_PROBE2(...) x, 1,

#define _INFO_IS_END2(a) _INFO_CHECK2(_INFO_CAT2(_INFO_IS_END2_, a))
#define _INFO_IS_END2__END _INFO_PROBE2(~)

#define _INFO_CHECK(...) _INFO_CHECK_B(__VA_ARGS__, 1,)
#define _INFO_CHECK_B(a,b,...) b
#define _INFO_PROBE(...) x, 0,

#define _INFO_IS_END(a) _INFO_CHECK(_INFO_CAT(_INFO_IS_END_, a))
#define _INFO_IS_END__END _INFO_PROBE(~)

#define _INFO_IF(c) _INFO_CAT(_INFO_IF_, c)
#define _INFO_IF_0(t,...) t
#define _INFO_IF_1(t,...) __VA_ARGS__


#define _INFO_IF2(c) _INFO_CAT2(_INFO_IF2_, c)
#define _INFO_IF2_1(t,...) t
#define _INFO_IF2_0(t,...) __VA_ARGS__

#define _INFO_CHECK_FALSE(x, ...) a,b
#define _INFO_RECURSE_IND() _INFO_RECURSE_
#define _INFO_RECURSE_(G, a, ...) _INFO_IF(_INFO_IS_END(a))(_END, (_INFO_CAT(G,a), _INFO_DEFER4(_INFO_RECURSE_IND)()(G, __VA_ARGS__)))
#define _INFO_RECURSE(G, ...) _INFO_RECURSE_(G, __VA_ARGS__, _END,)

#endif // INFO_GEN_H_
